site_name: Finance Perso
site_url: https://soragxyz.github.io/finance/
repo_url: https://github.com/soragXYZ/finance
repo_name: soragXYZ/finance
edit_uri: edit/main/docs/

theme:
  name: material
  favicon: favicon.png
  icon:
    logo: material/facebook-gaming
  font:
    text: Roboto

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
  features:
    - navigation.indexes
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - navigation.footer
    - toc.follow
    - content.action.edit
    - content.action.view

nav:
  - Accueil: 'index.md'
  - Livrets:
    - Qu'est-ce qu'un livret ?: livrets/description.md
    - Livret A: livrets/A.md
    - LEP: livrets/LEP.md
    - Livret Jeune: livrets/jeune.md
    - LDDS: livrets/LDDS.md
    - Autres livrets bancaires: livrets/autres.md
  - Autres:
    - Comparateurs: autre/comparateurs.md

markdown_extensions:
  - tables
  - md_in_html
  - attr_list
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
  - stylesheets/extra.css

extra:
  # Remove footer "Made with mkdocs"
  generator: false

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
  - git-committers:
      repository: soragXYZ/finance
      branch: main
      token: !!python/object/apply:os.getenv ["MKDOCS_GIT_COMMITTERS_APIKEY"]
